use std::sync::Arc;

use base64::{Engine as _, engine::general_purpose};
use futures::TryFutureExt;
use muon::client::flow::{ForkFlowResult, WithCodeFlow, WithCodePollFlow};
use proton_core_api::{
    auth::{KeySecret, UserKeySecret},
    services::{
        observability::ApiServiceObservabilityResponse,
        proton::{ProtonCore, SessionId},
    },
    session::SessionParts,
    store::{Store, UserData},
};
use proton_core_common::{Context, PassphraseAcquireError};
use proton_core_common::{
    metric,
    observability::{ObservabilityMetric, ObservabilityRecorder},
};
use proton_crypto_account::proton_crypto;
use proton_crypto_subtle::aead::{AesGcmCiphertext, AesGcmKey};
use regex::Regex;
use secrecy::ExposeSecret;
use serde::{Deserialize, Serialize};
use serde_json::json;
use thiserror::Error;

use crate::{
    ApiError,
    login::{LoginError, state::complete::Complete},
};

use super::State;

pub struct WantQrConfirmation {
    /// The user code used for the fork process
    pub user_code: String,
    /// The generated QR code in the form of: `qr_code_version:user_code:encryption_key_base64:client_id`
    pub qr_code: String,
    /// Secure random 32 byte key generated by the Target device
    pub encryption_key: KeySecret,
    pub parts: SessionParts,
    pub observability: ObservabilityRecorder,
    pub fork_flow: WithCodePollFlow,
}

impl WantQrConfirmation {
    /// Verifies host device confirmation for QR code login and completes the authentication process.
    ///
    /// This method checks for host device confirmation of the QR code login, decodes the payload using
    /// the provided encryption key, fetches user information, validates the passphrase, and stores user
    /// data. On success, it constructs a completed authentication state with session details.
    #[allow(clippy::too_many_lines)]
    pub async fn check_host_device_confirmation(self) -> Result<State, LoginError> {
        let (client, payload) = match self.fork_flow.poll().await {
            WithCodeFlow::Poll(flow) => {
                self.observability.record(
                    QrLoginPullFork {
                        status: QrLoginPullForkStatus::ForkPending,
                    },
                    true,
                );
                return Ok(State::WantQrConfirmation(WantQrConfirmation {
                    fork_flow: flow,
                    ..self
                }));
            }
            WithCodeFlow::Ok(client, payload) => {
                self.observability.record(
                    QrLoginPullFork {
                        status: QrLoginPullForkStatus::Success,
                    },
                    true,
                );
                (client, payload)
            }
            WithCodeFlow::Failed { reason, .. } => {
                self.observability.record(
                    QrLoginPullFork {
                        status: QrLoginPullForkStatus::Failure,
                    },
                    true,
                );
                return Err(LoginError::WithCodePollFlowFailed(reason.into()));
            }
        };
        info!("Host Device confirmed QR login");

        let passphrase = Self::decode_payload(payload, &self.encryption_key)
            .inspect_err(|err| {
                self.observability.record(
                    QrLoginPostLogin {
                        status: QrLoginPostLoginStatus::PayloadDecodeFailure,
                    },
                    true,
                );
                error!("{err}");
            })
            .map_err(|_| LoginError::QRLoginEncoding)?;
        let user = client
            .get_users()
            .await
            .inspect_err(|_| {
                self.observability.record(
                    QrLoginPostLogin {
                        status: QrLoginPostLoginStatus::UserFetchFailure,
                    },
                    true,
                );
            })
            .map(|res| res.user)
            .map_err(LoginError::UserFetch)?;
        let settings = client
            .get_settings()
            .map_ok(|res| res.user_settings)
            .map_err(LoginError::SettingsFetch)
            .await?;

        info!("Validate passpharse");
        let pgp = proton_crypto::new_pgp_provider();
        let passphrase = KeySecret::new(passphrase);
        let key_secret = if user.keys.unlock(&pgp, &passphrase).unlocked_keys.is_empty() {
            self.observability.record(
                QrLoginPostLogin {
                    status: QrLoginPostLoginStatus::KeySecretDecryptionFailure,
                },
                true,
            );
            return Err(LoginError::KeySecretDecryption);
        } else {
            UserKeySecret(passphrase)
        };

        let user_data = UserData {
            username: user.name.clone().unwrap_or_default(),
            display_name: user.display_name.clone().unwrap_or_default(),
            primary_addr: user.email.clone(),
            password_mode: settings.password.mode.into(),
            key_secret,
        };

        self.parts
            .store
            .write()
            .await
            .set_user_data(user_data)
            .await?;

        let auth = self.parts.store.write().await.get_auth().await;

        self.observability.record(
            QrLoginPostLogin {
                status: QrLoginPostLoginStatus::Success,
            },
            true,
        );

        let data = super::StateData {
            parts: self.parts,
            user_id: user.id.clone(),
            session_id: SessionId::new(auth.uid().unwrap_or_default().to_owned()),
            observability: self.observability,
        };
        info!("QR Login was successful");
        Ok(State::Complete(Complete::new(client, data, Some(user))))
    }

    fn decode_payload(
        payload: Option<Vec<u8>>,
        encryption_key: &KeySecret,
    ) -> Result<Vec<u8>, String> {
        let Some(payload) = payload.filter(|it| !it.is_empty()) else {
            return Ok(Vec::default());
        };
        let key = AesGcmKey::from_bytes(encryption_key.as_bytes())
            .map_err(|err| format!("Invalid key: {err}"))?;

        // At this point, it's unknown whether the payload was encrypted in legacy or non-legacy mode, so unfortunately, we have to try both.
        // Try legacy decryption first
        info!("Try legacy decryption");
        let decrypted_payload_bytes = {
            let cipthertext = AesGcmCiphertext::decode_legacy(&payload)
                .map_err(|err| format!("Failed to decode legacy payload: {err}"))?;

            // cipthertext -> bytes
            key.decrypt_legacy(cipthertext, None)
                .map_err(|err| format!("Failed to decrypt legacy payload: {err}"))
        };
        // Then non-legacy
        let decrypted_payload_bytes = decrypted_payload_bytes.or_else(|_err| {
            info!("Legacy decryption failed, let's try non-legacy one");

            let cipthertext = AesGcmCiphertext::decode(&payload)
                .map_err(|err| format!("Failed to decode payload: {err}"))?;

            // cipthertext -> bytes
            key.decrypt(cipthertext, None)
                .map_err(|err| format!("Failed to decrypt payload: {err}"))
        })?;
        // bytes -> UTF8 String
        let decrypted_payload = String::from_utf8(decrypted_payload_bytes)
            .map_err(|err| format!("Failed to parse decrypted payload to valid UTF8: {err}"))?;
        // UTF8 String -> JSON
        let json: serde_json::Value = serde_json::from_str(&decrypted_payload)
            .map_err(|err| format!("Failed to parse payload into JSON: {err}"))?;
        // JSON keyPassword field
        let key_password = json
            .get("keyPassword")
            .ok_or(String::from("Missing keyPassword field"))?
            .as_str()
            .ok_or(String::from("keyPassword  field is not a string"))?;
        Ok(key_password.as_bytes().to_vec())
    }
}

#[derive(Error, Debug)]
pub enum ParseError {
    #[error("Invalid format: {0}")]
    InvalidFormat(String),
    #[error("Version must be 0, got {0}")]
    InvalidVersion(String),
    #[error("User code cannot be empty")]
    EmptyUserCode,
    #[error("Encryption key must be 32 bytes, got {0} bytes")]
    InvalidEncryptionKeyLength(usize),
    #[error("Client ID cannot be empty")]
    EmptyClientId,
    #[error("Failed to decode Base64 encryption key: {0}")]
    Base64DecodeError(#[from] base64::DecodeError),
    #[error("Failed to parse version: {0}")]
    VersionParseError(String),
}

#[derive(Debug)]
pub struct SignInQrCodeValues {
    pub version: u32,
    pub user_code: String,
    pub encryption_key: Option<Vec<u8>>,
    pub client_id: String,
}

#[derive(Error, Debug)]
pub enum ProcessTargetDeviceQrError {
    #[error("Parsing failed: {0}")]
    ParseError(#[from] ParseError),

    #[error("Encryption failed: {0}")]
    EncryptionFailed(#[from] EncryptionError),

    #[error("API call failed: {0}")]
    Api(#[from] ApiError),

    #[error("Failed to acquire passphrase")]
    PassphraseAcquire(#[from] PassphraseAcquireError),
}

/// Processes a QR code from a Target Device to initiate a secure session fork.
///
/// This function parses the provided QR code, retrieves the current device's session passphrase,
/// encrypts it using the encryption key from the QR code, and sends a fork confirmation
/// to the Target Device.
/// If the encryption key is missing from the QR code, the passphrase is not sent as part of the fork confirmation payload.
pub async fn process_target_device_qr_code(
    qr_code: &str,
    client: muon::Client,
    context: Arc<Context>,
    observability: ObservabilityRecorder,
) -> Result<(), ProcessTargetDeviceQrError> {
    let qr_data = parse_qr_string(qr_code)
        .inspect(|_| observability.record(QrLoginDecodeQR::success(), true))
        .inspect_err(|e| observability.record(QrLoginDecodeQR::failure(e), true))?;
    let fork_confirmation =
        if let Some(encryption_key) = qr_data.encryption_key.filter(|it| !it.is_empty()) {
            // Encrypt this device's passphrase with the encryption key from the Target Device's QR code
            let passphrase = context.get_session_passphrase().await?;
            // Passphrase is a valid utf8 string
            let passphrase_str = String::from_utf8_lossy(passphrase.expose_secret());
            let key = AesGcmKey::from_bytes(&encryption_key)
                .map_err(|err| format!("Invalid key: {err}"))
                .unwrap();
            let json = json!({
                "type": "default",
                "keyPassword": passphrase_str,
            });
            let payload = key.encrypt_legacy(json.to_string(), None).unwrap();
            client
                .clone()
                .fork(qr_data.client_id)
                .payload(payload.encode())
        } else {
            client.clone().fork(qr_data.client_id)
        };

    match fork_confirmation
        .independent()
        .code(&qr_data.user_code)
        .send()
        .await
    {
        ForkFlowResult::Success(_client, _selector) => {
            observability.record(
                QrLoginPushFork {
                    status: ApiServiceObservabilityResponse::Success,
                },
                true,
            );
            Ok(())
        }
        ForkFlowResult::Failure { reason, .. } => {
            observability.record(
                QrLoginPushFork {
                    status: ApiServiceObservabilityResponse::NetworkError,
                },
                true,
            );
            Err(ProcessTargetDeviceQrError::Api(ApiError::Muon(
                reason.into(),
            )))
        }
    }
}

/// Parses the sign in QR code string of the target device and extracts its components with validation.
pub fn parse_qr_string(input: &str) -> Result<SignInQrCodeValues, ParseError> {
    let re = Regex::new(r"^([^:]*):([^:]*):([^:]*):([^:]*)$")
        .map_err(|_| ParseError::InvalidFormat("Failed to compile regex".to_string()))?;

    let captures = re
        .captures(input)
        .ok_or_else(|| ParseError::InvalidFormat(input.to_string()))?;

    let version_str = captures
        .get(1)
        .ok_or_else(|| ParseError::InvalidFormat("Missing version".to_string()))?
        .as_str();
    let user_code = captures
        .get(2)
        .ok_or_else(|| ParseError::InvalidFormat("Missing user code".to_string()))?
        .as_str()
        .to_string();
    let encryption_key_base64 = captures
        .get(3)
        .ok_or_else(|| ParseError::InvalidFormat("Missing encryption key".to_string()))?
        .as_str();
    let client_id = captures
        .get(4)
        .ok_or_else(|| ParseError::InvalidFormat("Missing client ID".to_string()))?
        .as_str()
        .to_string();

    // Validate version
    let version = version_str
        .parse::<u32>()
        .map_err(|_| ParseError::VersionParseError(version_str.to_string()))?;
    if version != 0 {
        return Err(ParseError::InvalidVersion(version_str.to_string()));
    }

    if user_code.is_empty() {
        return Err(ParseError::EmptyUserCode);
    }

    // Validate encryption key (if not empty)
    let encryption_key = if encryption_key_base64.is_empty() {
        None
    } else {
        let decoded_key = general_purpose::STANDARD.decode(encryption_key_base64)?;
        if decoded_key.len() != 32 {
            return Err(ParseError::InvalidEncryptionKeyLength(decoded_key.len()));
        }
        Some(decoded_key)
    };

    if client_id.is_empty() {
        return Err(ParseError::EmptyClientId);
    }

    Ok(SignInQrCodeValues {
        version,
        user_code,
        encryption_key,
        client_id,
    })
}

#[derive(Error, Debug)]
pub enum EncryptionError {
    #[error("Invalid key length: expected 32 bytes, got {0} bytes")]
    InvalidKeyLength(usize),
    #[error("Invalid data length: got {0} bytes")]
    InvalidDataLength(usize),
    #[error("Invalid nonce length: got {0} bytes")]
    InvalidNonceLength(usize),
    #[error("Decryption failed: {0}")]
    EncryptionFailed(#[from] aes_gcm::Error),
    #[error("Base64 decoding failed: {0}")]
    InvalidBase64(base64::DecodeError),
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
enum QrLoginPullForkStatus {
    Success,
    ForkPending,
    Failure,
}

metric! {
    #[name = "core_qr_login_pull_fork_total"]
    #[version = 1]
    #[doc = "Records the outcomes of the `GET auth/v4/sessions/forks/{selector}` API call on the target device."]
    pub struct QrLoginPullFork {
        pub status: QrLoginPullForkStatus
    }
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
enum QrLoginPostLoginStatus {
    Success,
    PayloadDecodeFailure,
    UserFetchFailure,
    KeySecretDecryptionFailure,
}

metric! {
    #[name = "core_qr_login_post_login_total"]
    #[version = 1]
    #[doc = "Records the outcomes of the post-login steps on the target device."]
    pub struct QrLoginPostLogin {
        pub status: QrLoginPostLoginStatus
    }
}

metric! {
    #[name = "core_qr_login_push_fork_total"]
    #[version = 1]
    #[doc = "Records the outcomes of the `POST auth/v4/sessions/forks` API call on the origin device."]
    pub struct QrLoginPushFork {
        pub status: ApiServiceObservabilityResponse
    }
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
enum QrLoginDecodeQrStatus {
    Success,
    InvalidFormat,
    InvalidVersion,
    EmptyUserCode,
    InvalidEncryptionKeyLength,
    EmptyClientId,
    Base64DecodeError,
    VersionParseError,
}

impl From<&ParseError> for QrLoginDecodeQrStatus {
    fn from(value: &ParseError) -> Self {
        match value {
            ParseError::InvalidFormat(_) => Self::InvalidFormat,
            ParseError::InvalidVersion(_) => Self::InvalidVersion,
            ParseError::EmptyUserCode => Self::EmptyUserCode,
            ParseError::InvalidEncryptionKeyLength(_) => Self::InvalidEncryptionKeyLength,
            ParseError::EmptyClientId => Self::EmptyClientId,
            ParseError::Base64DecodeError(_) => Self::Base64DecodeError,
            ParseError::VersionParseError(_) => Self::VersionParseError,
        }
    }
}

metric! {
    #[name = "core_qr_login_decode_qr_total"]
    #[version = 1]
    #[doc = "Records the outcomes of decoding the QR code on the origin device."]
    pub struct QrLoginDecodeQR {
        pub status: QrLoginDecodeQrStatus
    }
}

impl QrLoginDecodeQR {
    fn failure(e: &ParseError) -> Self {
        QrLoginDecodeQR { status: e.into() }
    }

    fn success() -> Self {
        QrLoginDecodeQR {
            status: QrLoginDecodeQrStatus::Success,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_valid_input() {
        let input = "0:abc123:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=:client1";
        let result = parse_qr_string(input);
        match result {
            Ok(data) => {
                assert_eq!(data.version, 0);
                assert_eq!(data.user_code, "abc123");
                assert_eq!(data.encryption_key.map(|key| key.len()), Some(32));
                assert_eq!(data.client_id, "client1");
            }
            Err(e) => panic!("Expected Ok, got Err: {e}"),
        }
    }

    #[test]
    fn test_no_encryption_key() {
        let input = "0:abc123::client1";
        let result = parse_qr_string(input);
        match result {
            Ok(data) => {
                assert_eq!(data.version, 0);
                assert_eq!(data.user_code, "abc123");
                assert!(data.encryption_key.is_none());
                assert_eq!(data.client_id, "client1");
            }
            Err(e) => panic!("Expected Ok, got Err: {e}"),
        }
    }

    #[test]
    fn test_invalid_format() {
        let input = "0:abc123:invalid";
        let result = parse_qr_string(input);
        assert!(matches!(result, Err(ParseError::InvalidFormat(_))));
    }

    #[test]
    fn test_invalid_version() {
        let input = "1:abc123::client1";
        let result = parse_qr_string(input);
        assert!(matches!(result, Err(ParseError::InvalidVersion(_))));
    }

    #[test]
    fn test_empty_user_code() {
        let input = "0::AA==:client1";
        let result = parse_qr_string(input);
        assert!(matches!(result, Err(ParseError::EmptyUserCode)));
    }

    #[test]
    fn test_invalid_encryption_key_length() {
        let input = "0:abc123:AA==:client1"; // Base64 decodes to 1 byte
        let result = parse_qr_string(input);
        assert!(matches!(
            result,
            Err(ParseError::InvalidEncryptionKeyLength(1))
        ));
    }

    #[test]
    fn test_empty_client_id() {
        let input = "0:abc123::";
        let result = parse_qr_string(input);
        assert!(matches!(result, Err(ParseError::EmptyClientId)));
    }

    #[test]
    fn test_invalid_base64() {
        let input = "0:abc123:invalid-base64:client1";
        let result = parse_qr_string(input);
        assert!(matches!(result, Err(ParseError::Base64DecodeError(_))));
    }
}
