use std::sync::Arc;

use aes_gcm::{
    AesGcm, KeyInit as _, Nonce,
    aead::{Aead as _, consts::U16},
    aes::Aes256,
};
use base64::{Engine as _, engine::general_purpose};
use futures::TryFutureExt as _;
use muon::client::flow::{WithCodeFlow, WithCodePollFlow};
use proton_core_api::{
    auth::{KeySecret, UserKeySecret},
    services::{
        observability::ObservabilityRecorder,
        proton::{ProtonCore, SessionId},
    },
    session::SessionParts,
    store::{Store, UserData},
};
use proton_core_common::{Context, PassphraseAcquireError};
use proton_crypto_account::proton_crypto::{self, generate_secure_random_bytes};
use regex::Regex;
use secrecy::ExposeSecret;
use serde_json::json;
use thiserror::Error;

use crate::{
    ApiError,
    login::{LoginError, state::complete::Complete},
};

use super::State;

pub struct WantQrConfirmation {
    /// The user code used for the fork process
    pub user_code: String,
    /// The generated QR code in the form of: `qr_code_version:user_code:encryption_key_base64:client_id`
    pub qr_code: String,
    /// Secure random 32 byte key generated by the Target device
    pub encryption_key: KeySecret,
    pub parts: SessionParts,
    pub observability: ObservabilityRecorder,
    pub fork_flow: WithCodePollFlow,
}

impl WantQrConfirmation {
    /// Verifies host device confirmation for QR code login and completes the authentication process.
    ///
    /// This method checks for host device confirmation of the QR code login, decodes the payload using
    /// the provided encryption key, fetches user information, validates the passphrase, and stores user
    /// data. On success, it constructs a completed authentication state with session details.
    pub async fn check_host_device_confirmation(self) -> Result<State, LoginError> {
        let (client, payload) = match self.fork_flow.poll().await {
            WithCodeFlow::Poll(flow) => {
                return Ok(State::WantQrConfirmation(WantQrConfirmation {
                    fork_flow: flow,
                    ..self
                }));
            }
            WithCodeFlow::Ok(client, payload) => (client, payload),
            WithCodeFlow::Failed { reason, .. } => {
                return Err(LoginError::WithCodePollFlowFailed(reason.into()));
            }
        };
        info!("Host Device confirmed QR login");

        let passphrase = Self::decode_payload(payload, &self.encryption_key)
            .inspect_err(|err| error!("{err}"))
            .map_err(|_| LoginError::QRLoginEncoding)?;

        let user = client
            .get_users()
            .map_ok(|res| res.user)
            .map_err(LoginError::UserFetch)
            .await?;

        info!("Validate passphrarse");
        let pgp = proton_crypto::new_pgp_provider();
        let passphrase = KeySecret::new(passphrase);
        let key_secret = if user.keys.unlock(&pgp, &passphrase).unlocked_keys.is_empty() {
            return Err(LoginError::KeySecretDecryption);
        } else {
            UserKeySecret(passphrase)
        };
        let user_data = UserData {
            username: user.name.clone().unwrap_or_default(),
            display_name: user.display_name.clone().unwrap_or_default(),
            primary_addr: user.email.clone(),
            key_secret,
        };
        self.parts
            .store
            .write()
            .await
            .set_user_data(user_data)
            .await?;

        let auth = self.parts.store.write().await.get_auth().await;

        let data = super::StateData {
            parts: self.parts,
            user_id: user.id.clone(),
            session_id: SessionId::new(auth.uid().unwrap_or_default().to_owned()),
            observability: self.observability,
        };
        info!("QR Login was successful");
        Ok(State::Complete(Complete::new(client, data, Some(user))))
    }

    fn decode_payload(
        payload: Option<Vec<u8>>,
        encryption_key: &KeySecret,
    ) -> Result<Vec<u8>, String> {
        let Some(payload) = payload.filter(|it| !it.is_empty()) else {
            return Ok(Vec::default());
        };
        let decrypted_payload_bytes = decrypt(&payload, encryption_key.as_bytes())
            .map_err(|err| format!("Failed to decode payload: {err}"))?;
        let decrypted_payload = String::from_utf8(decrypted_payload_bytes)
            .map_err(|err| format!("Failed to parse decrypted payload to valid UTF8: {err}"))?;
        let json: serde_json::Value = serde_json::from_str(&decrypted_payload)
            .map_err(|err| format!("Failed to parse payload into JSON: {err}"))?;
        let key_password = json
            .get("keyPassword")
            .ok_or(String::from("Missing keyPassword field"))?
            .as_str()
            .ok_or(String::from("keyPassword  field is not a string"))?;
        Ok(key_password.as_bytes().to_vec())
    }
}

#[derive(Error, Debug)]
pub enum ParseError {
    #[error("Invalid format: {0}")]
    InvalidFormat(String),
    #[error("Version must be 0, got {0}")]
    InvalidVersion(String),
    #[error("User code cannot be empty")]
    EmptyUserCode,
    #[error("Encryption key must be 32 bytes, got {0} bytes")]
    InvalidEncryptionKeyLength(usize),
    #[error("Client ID cannot be empty")]
    EmptyClientId,
    #[error("Failed to decode Base64 encryption key: {0}")]
    Base64DecodeError(#[from] base64::DecodeError),
    #[error("Failed to parse version: {0}")]
    VersionParseError(String),
}

#[derive(Debug)]
pub struct SignInQrCodeValues {
    pub version: u32,
    pub user_code: String,
    pub encryption_key: Option<Vec<u8>>,
    pub client_id: String,
}

#[derive(Error, Debug)]
pub enum ProcessTargetDeviceQrError {
    #[error("Parsing failed: {0}")]
    ParseError(#[from] ParseError),

    #[error("Encryption failed: {0}")]
    EncryptionFailed(#[from] EncryptionError),

    #[error("API call failed: {0}")]
    Api(#[from] ApiError),

    #[error("Failed to acquire passphrase")]
    PassphraseAcquire(#[from] PassphraseAcquireError),
}

/// Processes a QR code from a Target Device to initiate a secure session fork.
///
/// This function parses the provided QR code, retrieves the current device's session passphrase,
/// encrypts it using the encryption key from the QR code, and sends a fork confirmation
/// to the Target Device.
/// If the encryption key is missing from the QR code, the passphrase is not sent as part of the fork confirmation payload.
pub async fn process_target_device_qr_code(
    qr_code: &str,
    client: muon::Client,
    context: Arc<Context>,
) -> Result<(), ProcessTargetDeviceQrError> {
    let qr_data = parse_qr_string(qr_code)?;

    let fork_confirmation =
        if let Some(encryption_key) = qr_data.encryption_key.filter(|it| !it.is_empty()) {
            // Encrypt this device's passphrase with the encryption key from the Target Device's QR code
            let passphrase = context.get_session_passphrase().await?;
            // Passphrase is a valid utf8 string
            let passphrase_str = String::from_utf8_lossy(passphrase.expose_secret());
            let json = json!({
                "type": "default",
                "keyPassword": passphrase_str,
            });
            let payload = encrypt(&json.to_string(), &encryption_key)?;
            client
                .clone()
                .fork(context.get_client_id())
                .payload(payload)
        } else {
            client.clone().fork(context.get_client_id())
        };
    fork_confirmation
        .independent()
        .code(&qr_data.user_code)
        .send()
        .await;
    Ok(())
}

/// Parses the sign in QR code string of the target device and extracts its components with validation.
pub fn parse_qr_string(input: &str) -> Result<SignInQrCodeValues, ParseError> {
    let re = Regex::new(r"^([^:]*):([^:]*):([^:]*):([^:]*)$")
        .map_err(|_| ParseError::InvalidFormat("Failed to compile regex".to_string()))?;

    let captures = re
        .captures(input)
        .ok_or_else(|| ParseError::InvalidFormat(input.to_string()))?;

    let version_str = captures
        .get(1)
        .ok_or_else(|| ParseError::InvalidFormat("Missing version".to_string()))?
        .as_str();
    let user_code = captures
        .get(2)
        .ok_or_else(|| ParseError::InvalidFormat("Missing user code".to_string()))?
        .as_str()
        .to_string();
    let encryption_key_base64 = captures
        .get(3)
        .ok_or_else(|| ParseError::InvalidFormat("Missing encryption key".to_string()))?
        .as_str();
    let client_id = captures
        .get(4)
        .ok_or_else(|| ParseError::InvalidFormat("Missing client ID".to_string()))?
        .as_str()
        .to_string();

    // Validate version
    let version = version_str
        .parse::<u32>()
        .map_err(|_| ParseError::VersionParseError(version_str.to_string()))?;
    if version != 0 {
        return Err(ParseError::InvalidVersion(version_str.to_string()));
    }

    if user_code.is_empty() {
        return Err(ParseError::EmptyUserCode);
    }

    // Validate encryption key (if not empty)
    let encryption_key = if encryption_key_base64.is_empty() {
        None
    } else {
        let decoded_key = general_purpose::STANDARD.decode(encryption_key_base64)?;
        if decoded_key.len() != 32 {
            return Err(ParseError::InvalidEncryptionKeyLength(decoded_key.len()));
        }
        Some(decoded_key)
    };

    if client_id.is_empty() {
        return Err(ParseError::EmptyClientId);
    }

    Ok(SignInQrCodeValues {
        version,
        user_code,
        encryption_key,
        client_id,
    })
}

#[derive(Error, Debug)]
pub enum EncryptionError {
    #[error("Invalid key length: expected 32 bytes, got {0} bytes")]
    InvalidKeyLength(usize),
    #[error("Invalid data length: got {0} bytes")]
    InvalidDataLength(usize),
    #[error("Invalid nonce length: got {0} bytes")]
    InvalidNonceLength(usize),
    #[error("Decryption failed: {0}")]
    EncryptionFailed(#[from] aes_gcm::Error),
    #[error("Base64 decoding failed: {0}")]
    InvalidBase64(base64::DecodeError),
}

const NONCE_LENGTH: usize = 16;
const TAG_LENGTH: usize = 16;

// TODO https://protonag.atlassian.net/browse/ET-3413
/// Encrypts a payload string using AES-256-GCM with a 16-byte IV and 16-byte authentication tag.
/// Returns output formatted as: IV (16 bytes) | ciphertext | tag (16 bytes).
pub fn encrypt(payload: &str, key: &[u8]) -> Result<Vec<u8>, EncryptionError> {
    if key.len() != 32 {
        return Err(EncryptionError::InvalidKeyLength(key.len()));
    }

    let cipher = AesGcm::<Aes256, U16>::new_from_slice(key)
        .map_err(|_| EncryptionError::InvalidKeyLength(key.len()))?;

    let iv: [u8; NONCE_LENGTH] = generate_secure_random_bytes();
    let nonce = Nonce::<U16>::from_slice(&iv);

    let ciphertext_with_tag = cipher.encrypt(nonce, payload.as_bytes())?;

    // Split ciphertext and tag
    let ciphertext_len = ciphertext_with_tag.len() - TAG_LENGTH;
    let ciphertext = &ciphertext_with_tag[..ciphertext_len];
    let tag = &ciphertext_with_tag[ciphertext_len..];

    // Construct output: IV | ciphertext | tag
    let mut output = Vec::with_capacity(NONCE_LENGTH + ciphertext.len() + TAG_LENGTH);
    output.extend_from_slice(&iv);
    output.extend_from_slice(ciphertext);
    output.extend_from_slice(tag);
    Ok(output)
}

/// Decrypts an AES-256-GCM encrypted payload formatted as: IV (16 bytes) | ciphertext | tag (16 bytes).
pub fn decrypt(data: &[u8], key: &[u8]) -> Result<Vec<u8>, EncryptionError> {
    if key.len() != 32 {
        return Err(EncryptionError::InvalidKeyLength(key.len()));
    }

    if data.len() < NONCE_LENGTH + TAG_LENGTH {
        return Err(EncryptionError::InvalidDataLength(data.len()));
    }

    // Extract IV, ciphertext, and tag
    let iv = &data[..NONCE_LENGTH];
    let ciphertext_end = data.len() - TAG_LENGTH;
    let ciphertext = &data[NONCE_LENGTH..ciphertext_end];
    let tag = &data[ciphertext_end..];

    // Reconstruct ciphertext with tag for decryption
    let mut ciphertext_with_tag = Vec::with_capacity(ciphertext.len() + TAG_LENGTH);
    ciphertext_with_tag.extend_from_slice(ciphertext);
    ciphertext_with_tag.extend_from_slice(tag);

    // Create nonce from IV
    let nonce = Nonce::<U16>::from_slice(iv);

    let cipher = AesGcm::<Aes256, U16>::new_from_slice(key)
        .map_err(|_| EncryptionError::InvalidKeyLength(key.len()))?;

    let plaintext = cipher.decrypt(nonce, ciphertext_with_tag.as_slice())?;

    Ok(plaintext)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_valid_input() {
        let input = "0:abc123:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=:client1";
        let result = parse_qr_string(input);
        match result {
            Ok(data) => {
                assert_eq!(data.version, 0);
                assert_eq!(data.user_code, "abc123");
                assert_eq!(data.encryption_key.map(|key| key.len()), Some(32));
                assert_eq!(data.client_id, "client1");
            }
            Err(e) => panic!("Expected Ok, got Err: {e}"),
        }
    }

    #[test]
    fn test_no_encryption_key() {
        let input = "0:abc123::client1";
        let result = parse_qr_string(input);
        match result {
            Ok(data) => {
                assert_eq!(data.version, 0);
                assert_eq!(data.user_code, "abc123");
                assert!(data.encryption_key.is_none());
                assert_eq!(data.client_id, "client1");
            }
            Err(e) => panic!("Expected Ok, got Err: {e}"),
        }
    }

    #[test]
    fn test_invalid_format() {
        let input = "0:abc123:invalid";
        let result = parse_qr_string(input);
        assert!(matches!(result, Err(ParseError::InvalidFormat(_))));
    }

    #[test]
    fn test_invalid_version() {
        let input = "1:abc123::client1";
        let result = parse_qr_string(input);
        assert!(matches!(result, Err(ParseError::InvalidVersion(_))));
    }

    #[test]
    fn test_empty_user_code() {
        let input = "0::AA==:client1";
        let result = parse_qr_string(input);
        assert!(matches!(result, Err(ParseError::EmptyUserCode)));
    }

    #[test]
    fn test_invalid_encryption_key_length() {
        let input = "0:abc123:AA==:client1"; // Base64 decodes to 1 byte
        let result = parse_qr_string(input);
        assert!(matches!(
            result,
            Err(ParseError::InvalidEncryptionKeyLength(1))
        ));
    }

    #[test]
    fn test_empty_client_id() {
        let input = "0:abc123::";
        let result = parse_qr_string(input);
        assert!(matches!(result, Err(ParseError::EmptyClientId)));
    }

    #[test]
    fn test_invalid_base64() {
        let input = "0:abc123:invalid-base64:client1";
        let result = parse_qr_string(input);
        assert!(matches!(result, Err(ParseError::Base64DecodeError(_))));
    }

    fn generate_key() -> Vec<u8> {
        vec![0_u8; 32]
    }

    #[test]
    fn test_encrypt_valid_payload() {
        let payload = "Hello, world!";
        let key = generate_key();
        let result = encrypt(payload, &key);
        assert!(
            result.unwrap().len() >= NONCE_LENGTH + TAG_LENGTH,
            "Output should include ciphertext, tag, and nonce"
        );
    }

    #[test]
    fn test_encrypt_empty_payload() {
        let key = generate_key();
        let result = encrypt("", &key);
        assert!(result.is_ok());
    }

    #[test]
    fn test_encrypt_invalid_key_length() {
        let payload = "Hello, world!";
        let key = vec![0_u8; 16]; // Too short
        let result = encrypt(payload, &key);
        assert!(matches!(result, Err(EncryptionError::InvalidKeyLength(16))));
    }

    #[test]
    fn test_decrypt_valid_data() {
        let payload = "Hello, world!";
        let key = generate_key();
        let encrypted = encrypt(payload, &key).expect("Encryption should succeed");
        let result = decrypt(&encrypted, &key);
        assert!(result.is_ok(), "Decryption should succeed");
        let decrypted = result.unwrap();
        assert_eq!(
            decrypted,
            payload.as_bytes(),
            "Decrypted data should match original"
        );
    }

    #[test]
    fn test_decrypt_invalid_key_length() {
        let payload = "Hello, world!";
        let key = generate_key();
        let encrypted = encrypt(payload, &key).expect("Encryption should succeed");
        let invalid_key = vec![0_u8; 16]; // Too short
        let result = decrypt(&encrypted, &invalid_key);
        assert!(matches!(result, Err(EncryptionError::InvalidKeyLength(16))));
    }

    #[test]
    fn test_decrypt_insufficient_data_length() {
        let key = generate_key();
        let data = vec![0_u8; NONCE_LENGTH + TAG_LENGTH - 1]; // Too short
        let result = decrypt(&data, &key);
        assert!(matches!(result, Err(EncryptionError::InvalidDataLength(_))));
    }

    #[test]
    fn test_encrypt_decrypt_round_trip() {
        let payloads = vec![
            "Test",
            "Hello, world!",
            "A longer test payload with spaces!",
        ];
        let key = generate_key();

        for payload in payloads {
            let encrypted = encrypt(payload, &key).expect("Encryption should succeed");
            let decrypted = decrypt(&encrypted, &key).expect("Decryption should succeed");
            assert_eq!(
                decrypted,
                payload.as_bytes(),
                "Round-trip should preserve payload"
            );
        }
    }
}
