include:
  - project: "rust/shared/registry"
    file: "upload_template.yml"

  - component: gitlab.protontech.ch/proton/devops/cicd-components/tools/github-mirror/ssh@0.0.3
    inputs:
      github-url: $SSH_MIRROR_GITHUB_URL
      vault-kv-path: "inbox-mobile_team/gitlab-projects/variables/${CI_PROJECT_ID}/github"
      vault-kv-field: ssh-key
      stage: github_mirror
      push-tags: true
      sync-from-branch: $CI_COMMIT_BRANCH
      sync-to-branch: $CI_COMMIT_BRANCH

workflow:
  rules:
    - if: $CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG =~ /^core-ical-v[0-9]+\.[0-9]+\.[0-9]+$/
    - if: $CI_COMMIT_TAG =~ /^mail-uniffi-v[0-9]+\.[0-9]+\.[0-9]+$/

default:
  image: harbor.protontech.ch/engineering-transformation/rust:rust-1.93.0
  tags:
    - shared-medium

variables:
  # Ensure submodules are fully initialized
  GIT_SUBMODULE_STRATEGY: recursive

  # The rust registry project
  RUST_REGISTRY: rust/shared/registry

  # The name of the registry
  RUST_REGISTRY_NAME: proton

  # The git URL of the rust registry
  RUST_REGISTRY_GIT_URL: ${CI_SERVER_PROTOCOL}://git:${RUST_REGISTRY_TOKEN}@${CI_SERVER_HOST}/${RUST_REGISTRY}.git

  GOFLAGS: "-buildvcs=false"

# Config git acccess to other repos
.script-config-git:
  script:
    - git config --global url.https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}.insteadOf https://${CI_SERVER_HOST}

stages:
  - lint
  - build
  - doc
  - deploy
  - github_mirror

migration-filenames-check:
  stage: lint
  script:
    - ./scripts/lint-migration-filenames/run.sh

audit:
  stage: lint
  script:
    - cargo install --locked --force cargo-audit
    - cargo audit

deny:
  stage: lint
  script:
    - !reference [ .script-config-git, script ]
  script:
    - cargo deny check sources

cargo-fmt:
  stage: lint
  script:
    - cargo fmt --check

taplo-fmt:
  stage: lint
  script:
    - taplo fmt --check

clippy:
  tags:
    - shared-large
  stage: lint
  script:
    - !reference [ .script-config-git, script ]
    - cargo clippy --all-targets -- -D warnings

gopenpgp:
  stage: lint
  script:
    - !reference [ .script-config-git, script ]
    - |
      pattern=".*gopenpgp-sys (v[0-9]+\\.[0-9]+\\.[0-9]+).*"
      version=""
      cargo tree |
      while read -r line
      do
          if [[ $line =~ $pattern ]]; then
              echo "Found gopenpgp-sys ${BASH_REMATCH[1]}"
              if [ -z "$version" ]; then
                  version=${BASH_REMATCH[1]}
              fi
              if [ "${BASH_REMATCH[1]}" != "$version" ]; then
                  echo "Multiple gopenpgp-sys versions found ${version}, ${BASH_REMATCH[1]}"
                  echo "Multiple go runtimes can cause issues at app runtime."
                  echo "Please unify the gopenpgp-sys versions in the dependency tree."
                  exit 1
              fi
          fi
      done

check-linux:
  tags:
    - shared-large
  stage: build
  script:
    - !reference [ .script-config-git, script ]
    - cargo check --release

test-linux:
  tags:
    - shared-large
  rules:
    - if: $CI_COMMIT_TAG !~ /^mail-uniffi-v[0-9]+\.[0-9]+\.[0-9]+$/
  needs:
    - check-linux
  stage: build
  script:
    - !reference [ .script-config-git, script ]
    - MOLD_JOBS=4 RUSTFLAGS="-C linker=clang -C link-arg=-fuse-ld=mold" cargo nextest run --color=never -j 8
    - MOLD_JOBS=4 RUSTFLAGS="-C linker=clang -C link-arg=-fuse-ld=mold" cargo test --doc

check-macos:
  tags:
    - inbox-tart
  image: "inbox-rust:1.93.0"
  stage: build
  script:
    - !reference [ .script-config-git, script ]
    - cargo check --release

test-macos:
  tags:
    - inbox-tart
  rules:
    - if: $CI_COMMIT_TAG !~ /^mail-uniffi-v[0-9]+\.[0-9]+\.[0-9]+$/
  image: "inbox-rust:1.93.0"
  stage: build
  needs:
    - check-macos
  script:
    - !reference [ .script-config-git, script ]
    - cargo nextest run --color=never -j4

.build-ical-php-ext:
  image: harbor.protontech.ch/storage/container/php-ext-builder:${ROCKY_VERSION}-${PHP_VERSION}-${BUILD_ARCH}
  variables:
    PHP: /usr/bin/php
    PHP_CONFIG: /usr/bin/php-config
  stage: build
  parallel:
    matrix:
      - ROCKY_VERSION: [ "8.9", "9.3" ]
        PHP_VERSION: [ "8.4", "8.5" ]
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "master"
      changes:
        - .gitlab-ci.yml
        - shared/ical/**/*
    - if: $CI_COMMIT_TAG =~ /^core-ical-v[0-9]+\.[0-9]+\.[0-9]+$/
  script:
    - !reference [ .script-config-git, script ]
    - . "$HOME/.cargo/env"
    - RUSTFLAGS="-C link-arg=-Wl,-undefined,dynamic_lookup" cargo +nightly build -p proton-ical --release --features php
    - cd shared/ical
    - mkdir -p build/ packages/${ROCKY_VERSION%%.*}
    - cd build/
    - cmake3 ../
    - cpack3 -G RPM ./
    - mv -v *.rpm ../packages/${ROCKY_VERSION%%.*}
    - mv ../packages ../../..
  artifacts:
    paths:
      - ./packages

build-ical-php-ext:amd64:
  extends: .build-ical-php-ext
  tags:
    - shared-medium
  variables:
    BUILD_ARCH: amd64

build-ical-php-ext:arm64:
  extends: .build-ical-php-ext
  tags:
    - m1-docker
  variables:
    BUILD_ARCH: arm64

publish-ical-php-ext:
  image: harbor.protontech.ch/storage/container/php-ext-builder:${ROCKY_VERSION}-${PHP_VERSION}-${BUILD_ARCH}
  stage: deploy
  needs:
    - build-ical-php-ext:amd64
    - build-ical-php-ext:arm64
  rules:
    - if: $CI_COMMIT_TAG =~ /^core-ical-v[0-9]+\.[0-9]+\.[0-9]+$/
  tags:
    - shared-small
  variables:
    # Note that this step actually deploys all of the artifacts, we just need
    # to provide some vars so that we can pick a Docker image (any variant would
    # work)
    ROCKY_VERSION: "9.3"
    PHP_VERSION: "8.4"
    BUILD_ARCH: amd64
    GIT_STRATEGY: none
  script:
    - set -e;
      pushd packages;
      for os_major in *; do
      pushd $os_major;
      for rpm in *.rpm; do
      arch=$(rpm -qp "$rpm" --qf "%{ARCH}");
      echo "Uploading ${os_major}/${arch}/$rpm";
      if [ "$NEXUS_UPLOADER_PASSWORD" = '' ]; then echo '$NEXUS_UPLOADER_PASSWORD is empty' >&2; exit 1; fi;
      curl -w '%{method} to %{url} -> %{http_code}\n' -f --progress-bar -u $NEXUS_UPLOADER_USERNAME:$NEXUS_UPLOADER_PASSWORD --upload-file $rpm "https://nexus.protontech.ch/repository/backend-team-rpm/el${os_major}/${arch}/";
      done;
      popd;
      done;
      popd;

build-mail-uniffi-ios:
  tags:
    - inbox-tart
  image: "inbox-rust:1.93.0"
  stage: build
  needs:
    - check-macos
  script:
    - !reference [ .script-config-git, script ]
    - rust-build/build_ios_framework_uniffi.sh proton-mail-uniffi ./mail/mail-uniffi/uniffi.toml "./tmp/ios-framework"
    - CRATE_VERSION=$(cargo metadata --format-version 1 --no-deps | jq '.packages[] | select(.name == "proton-mail-uniffi") | .version' | jq -r)
    - cd "./tmp/ios-framework/$CRATE_VERSION" && xcodebuild -scheme proton_app_uniffi -destination generic/platform=iOS -configuration="Release build"
  artifacts:
    name: proton-mail-ios
    paths:
      - tmp/ios-framework
    when: always
    expire_in: 4 hrs

build-mail-uniffi-android:
  tags:
    - android-xlarge
  stage: build
  needs:
    - check-linux
  script:
    - !reference [ .script-config-git, script ]
    - rust-build/build_android.sh proton-mail-uniffi ./mail/mail-uniffi/uniffi.toml ./mail/mail-uniffi/android/lib/src/main/
    - ./mail/mail-uniffi/android/build-android-archive.sh
  artifacts:
    name: proton-mail-android
    paths:
      - ./mail/mail-uniffi/android/lib/src/main
      - ./mail/mail-uniffi/android/lib/build/
    when: always
    expire_in: 4 hrs

pages:
  stage: doc
  script:
    - echo "CI_PAGES_URL = ${CI_PAGES_URL}"
    - !reference [ .script-config-git, script ]
    - cargo doc --workspace --no-deps --features sql --features test-utils
    - rm -rf public
    - mv target/doc public
    - echo "<meta http-equiv=\"refresh\" content=\"0; url=$CI_PAGES_URL/proton_mail_uniffi/index.html\">" > public/index.html
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    # allow to test pages in a MR
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
      allow_failure: true

.disabled-publish-crates:
  image: rustlang/rust:nightly
  stage: deploy
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
      variables: { DRY_RUN: "--dry-run" }
      allow_failure: true
    - when: manual
      variables: { DRY_RUN: "--dry-run" }
      allow_failure: true
  before_script:
    - apt-get update && apt-get install -y clang golang python3-packaging
    - cargo install --registry proton cargo-proton-utils
  script:
    - git stash --all
    - cargo proton-utils publish $DRY_RUN
      --registry $RUST_REGISTRY_NAME
      --repository $RUST_REGISTRY_GIT_URL
      --name $GITLAB_USER_NAME
      --email $GITLAB_USER_EMAIL
    - git stash pop

publish-mail-uniffi-android:
  stage: deploy
  tags:
    - shared-large
  rules:
    - if: $CI_COMMIT_TAG =~ /^mail-uniffi-v[0-9]+\.[0-9]+\.[0-9]+$/
  script:
    - !reference [ .script-config-git, script ]
    - ./mail/mail-uniffi/android/publish.sh
  dependencies:
    - build-mail-uniffi-android
  needs:
    - build-mail-uniffi-android
  artifacts:
    name: proton-mail-android-lib
    paths:
      - ./mail/mail-uniffi/android/lib/build/outputs/
    when: always
    expire_in: 4 hrs

publish-mail-uniffi-ios:
  stage: deploy
  tags:
    - shared-medium
  rules:
    - if: $CI_COMMIT_TAG =~ /^mail-uniffi-v[0-9]+\.[0-9]+\.[0-9]+$/
  script:
    - !reference [ .script-config-git, script ]
    - ./mail/mail-uniffi/ios/publish.sh
  dependencies:
    - build-mail-uniffi-ios
  needs:
    - build-mail-uniffi-ios

github-sync-ssh:
  image: "harbor.protontech.ch/devops/tools/github-mirror:0.0.3"
  stage: github_mirror
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: manual
      allow_failure: true
    - when: never
