SET(CPACK_GENERATOR "RPM")

SET(CPACK_PACKAGE_NAME ${PROJECT_NAME})
SET(CPACK_PACKAGE_CONTACT "Proton Technologies AG")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_SOURCE_DIR}/README.md")
SET(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
SET(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
SET(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})
SET(CPACK_PACKAGE_VERSION ${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH})
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "ical parser/generator/editor")
SET(CPACK_RESOURCE_FILE_README ${CMAKE_SOURCE_DIR}/README.md)
SET(CPACK_RESOURCE_FILE_WELCOME ${CMAKE_SOURCE_DIR}/README.md)
SET(CPACK_PACKAGE_DESCRIPTION_FILE ${CMAKE_SOURCE_DIR}/README.md)

SET(CPACK_RPM_PACKAGE_AUTOREQPROV "no")
SET(CPACK_RPM_PACKAGE_PROVIDES "libproton_ical")

SET(BASE_PACKAGE_NAME ${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION})
SET(CPACK_PACKAGE_FILE_NAME ${CPACK_PACKAGE_NAME}_${CPACK_PACKAGE_VERSION})

SET(CPACK_RPM_FILE_NAME "${BASE_PACKAGE_NAME}-php%{php_version}-%{_arch}.rpm")
SET(CPACK_RPM_PACKAGE_REQUIRES "php(api) = %{php_core_api}")

INSTALL(
    FILES ${CMAKE_CURRENT_SOURCE_DIR}/../../target/release/libproton_ical.so
    DESTINATION lib/
)

INCLUDE(CPack)
