image: gitlab.protontech.ch:4567/rust/inbox/docker-images:rust-1.77.0-nocache

include:
  - project: "rust/shared/registry"
    file: "upload_template.yml"

default:
  tags:
    - shared-medium

# Config git acccess to other repos
.script-config-git:
  script:
    - git config --global url.https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}.insteadOf https://${CI_SERVER_HOST}

stages:
  - lint
  - build
  - deploy

.do_fmt_check:
   script:
     - cargo fmt --check

.do_clippy_check:
   script:
     - !reference [.script-config-git, script]
     - cargo clippy -- -D warnings

format:
  stage: lint
  script:
    - !reference [.do_fmt_check, script]

clippy:
  stage: lint
  script:
    - !reference [.do_clippy_check, script]

build:
  stage: build
  script:
    - !reference [.script-config-git, script]
    - cargo build
    - cargo test

build-uniffi:
  stage: build
  script:
    - !reference [.script-config-git, script]
    - cargo build --features="uniffi"


build-android:
  stage: build
  script:
    - !reference [.script-config-git, script]
    - cargo ndk -t "armeabi-v7a" -t "arm64-v8a" -t "x86_64" build --release


build-macos:
  tags:
    - inbox-tart
  image: "inbox-rust:1.77.0"
  stage: build
  script:
    - !reference [.script-config-git, script]
    - cargo build --release
    - cargo test

build-ios:
  tags:
    - inbox-tart
  image: "inbox-rust:1.77.0"
  stage: build
  script:
    - !reference [.script-config-git, script]
    - cargo build --release --target --target x86_64-apple-ios
    - cargo build --release --target --target aarch64-apple-ios-sim
    - cargo build --release --target --target aarch64-apple-ios

# ------------ Crate Publishing -----------------------------------------------------------------------------------
# Crates are listed in the order they should be published

deploy-proton-async:
  extends: .deploy_to_protonvpn_repository
  image: gitlab.protontech.ch:4567/rust/inbox/docker-images:rust-1.77.0-nocache
  variables:
    CARGO_PACKAGE_OPTIONS: "--package proton-async"
  when: manual

deploy-proton-sqlite3:
  extends: .deploy_to_protonvpn_repository
  image: gitlab.protontech.ch:4567/rust/inbox/docker-images:rust-1.77.0-nocache
  variables:
    CARGO_PACKAGE_OPTIONS: "--package proton-sqlite3"
  when: manual

deploy-proton-api-core:
  extends: .deploy_to_protonvpn_repository
  tags:
    - shared-medium
  image: gitlab.protontech.ch:4567/rust/inbox/docker-images:rust-1.77.0-nocache
  variables:
    CARGO_PACKAGE_OPTIONS: "--package proton-api-core"
  when: manual

deploy-proton-action-queue:
  extends: .deploy_to_protonvpn_repository
  image: gitlab.protontech.ch:4567/rust/inbox/docker-images:rust-1.77.0-nocache
  tags:
    - shared-medium
  variables:
    CARGO_PACKAGE_OPTIONS: "--package proton-action-queue"
  when: manual

deploy-proton-event-loop:
  extends: .deploy_to_protonvpn_repository
  image: gitlab.protontech.ch:4567/rust/inbox/docker-images:rust-1.77.0-nocache
  tags:
    - shared-medium
  variables:
    CARGO_PACKAGE_OPTIONS: "--package proton-event-loop"
  when: manual

deploy-proton-core-common:
  extends: .deploy_to_protonvpn_repository
  image: gitlab.protontech.ch:4567/rust/inbox/docker-images:rust-1.77.0-nocache
  tags:
    - shared-medium
  variables:
    CARGO_PACKAGE_OPTIONS: "--package proton-core-common"
  when: manual
