[net]
git-fetch-with-cli = true

[registries.proton]
index = "sparse+https://rust.gitlab-pages.protontech.ch/shared/registry/index/"

[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/LBeernaertProton/rust-email_address.git?branch=feat/allow-long-local-parts"]
git = "https://github.com/LBeernaertProton/rust-email_address.git"
branch = "feat/allow-long-local-parts"
replace-with = "vendored-sources"

[source."git+https://github.com/frondeus/lightningcss?rev=b9dc136b0b43220381965e5806903e7c31a3ca12"]
git = "https://github.com/frondeus/lightningcss"
rev = "b9dc136b0b43220381965e5806903e7c31a3ca12"
replace-with = "vendored-sources"

[source."sparse+https://rust.gitlab-pages.protontech.ch/shared/registry/index/"]
registry = "sparse+https://rust.gitlab-pages.protontech.ch/shared/registry/index/"
replace-with = "vendored-sources"

[source."git+https://gitlab.protontech.ch/rust/inbox/muon.git?rev=4e410705f7becc18f1621eccc111211bc6c25345"]
git = "https://gitlab.protontech.ch/rust/inbox/muon.git"
rev = "4e410705f7becc18f1621eccc111211bc6c25345"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "3rdparty"
