CREATE TABLE mail_settings (
  local_id INTEGER PRIMARY KEY,
  almost_all_mail INTEGER NOT NULL,
  attach_public_key INTEGER NOT NULL,
  auto_delete_spam_and_trash_days INTEGER DEFAULT NULL,
  auto_save_contacts INTEGER NOT NULL DEFAULT 1,
  block_sender_confirmation INTEGER DEFAULT NULL,
  composer_mode INTEGER NOT NULL,
  confirm_link INTEGER NOT NULL DEFAULT 1,
  delay_send_seconds INTEGER NOT NULL DEFAULT 10,
  display_name TEXT NOT NULL,
  draft_mime_type INTEGER NOT NULL,
  enable_folder_color INTEGER NOT NULL,
  font_face TEXT DEFAULT NULL,
  hide_remote_images INTEGER NOT NULL,
  hide_embedded_images INTEGER NOT NULL,
  hide_sender_images INTEGER NOT NULL,
  image_proxy INTEGER NOT NULL,
  inherit_parent_folder_color INTEGER NOT NULL DEFAULT 1,
  message_buttons INTEGER NOT NULL,
  mobile_settings INTEGER DEFAULT NULL,
  next_message_on_move INTEGER DEFAULT NULL,
  num_message_per_page INTEGER NOT NULL,
  pgp_scheme INTEGER NOT NULL,
  pm_signature INTEGER NOT NULL,
  pm_signature_referral_link INTEGER NOT NULL DEFAULT 1,
  prompt_pin INTEGER NOT NULL,
  receive_mime_type INTEGER NOT NULL,
  right_to_left INTEGER NOT NULL,
  shortcuts INTEGER NOT NULL DEFAULT 1,
  show_images INTEGER NOT NULL,
  show_mime_type INTEGER NOT NULL,
  show_moved INTEGER NOT NULL,
  sign INTEGER NOT NULL,
  signature TEXT NOT NULL,
  spam_action INTEGER DEFAULT NULL,
  sticky_labels INTEGER NOT NULL,
  submission_access INTEGER NOT NULL,
  swipe_left INTEGER NOT NULL,
  swipe_right INTEGER NOT NULL,
  theme TEXT NOT NULL,
  view_layout INTEGER NOT NULL,
  view_mode INTEGER NOT NULL
)
