image: gitlab.protontech.ch:4567/rust/inbox/docker-images:rust-1.80.0

include:
  - project: "rust/shared/registry"
    file: "upload_template.yml"
  - project: "rust/rust-build"
    file: "rust-ci.yml"

workflow:
  rules:
    - if: $CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'

default:
  tags:
    - shared-medium

stages:
  - lint
  - build
  - doc
  - deploy

.do_proton_mail_uniffi_version:
  script:
    - cd proton_mail_uniffi

format:
  stage: lint
  script:
    - !reference [.do_fmt_check, script]

clippy:
  stage: lint
  script:
    - !reference [.do_clippy_check, script]

gopenpgp:
  stage: lint
  script:
    - !reference [.do_gopenpgp_sys_check, script]

build:
  tags:
    - shared-large
  stage: build
  script:
    - !reference [.script-config-git, script]
    - RUSTFLAGS="-C link-arg=-fuse-ld=lld" cargo build
    - RUSTFLAGS="-C link-arg=-fuse-ld=lld" cargo test

build-macos:
  tags:
    - inbox-tart
  image: "inbox-rust:1.80.0"
  stage: build
  script:
    - !reference [.script-config-git, script]
    - cargo build
    - cargo test

build-wasm:
  stage: build
  script:
    - !reference [.script-config-git, script]
    - cd proton-mail-wasm
    - wasm-pack build -d "./web_pkg"
  artifacts:
    name: proton-mail-wasm
    paths:
      - proton-mail-wasm/web_pkg
    when: always
    expire_in: 4 hrs

build-ios:
  tags:
    - inbox-tart
  image: "inbox-rust:1.80.0"
  stage: build
  script:
    - !reference [.script-config-git, script]
    - rust-build/build_ios_framework_uniffi.sh proton-mail-uniffi proton-mail-uniffi/uniffi.toml "./tmp/ios-framework"
    - CRATE_VERSION=$(cargo pkgid --manifest-path=proton-mail-uniffi/Cargo.toml | cut -d "#" -f2)
    - cd "./tmp/ios-framework/$CRATE_VERSION" && xcodebuild -scheme proton_app_uniffi -destination generic/platform=iOS -configuration="Release build"

  artifacts:
    name: proton-mail-ios
    paths:
      - tmp/ios-framework
    when: always
    expire_in: 4 hrs

build-android:
  stage: build
  script:
    - !reference [.script-config-git, script]
    - rust-build/build_android.sh proton-mail-uniffi proton-mail-uniffi/uniffi.toml ./proton-mail-uniffi/android/lib/src/main/
    - ./proton-mail-uniffi/android/build-android-archive.sh

  artifacts:
    name: proton-mail-android
    paths:
      - ./proton-mail-uniffi/android/lib/src/main
      - ./proton-mail-uniffi/android/lib/build/
    when: always
    expire_in: 4 hrs

pages:
  stage: doc
  script:
    - echo "CI_PAGES_URL = ${CI_PAGES_URL}"
    - !reference [.script-config-git, script]
    - cargo doc --workspace --all-features --no-deps
    - rm -rf public
    - mv target/doc public
    - echo "<meta http-equiv=\"refresh\" content=\"0; url=$CI_PAGES_URL/proton_mail_uniffi/index.html\">" > public/index.html
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
      allow_failure: true
    # allow to test pages in a MR
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
      allow_failure: true

publish-android:
  stage: deploy
  tags:
    - xlarge-k8s
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
      when: always
      allow_failure: true
  script:
    - ./proton-mail-uniffi/android/publish.sh
  dependencies:
    - build-android
  needs:
    - build-android
  artifacts:
    name: proton-mail-android-lib
    paths:
      - ./proton-mail-uniffi/android/lib/build/outputs/
    when: always
    expire_in: 4 hrs

publish-ios:
  stage: deploy
  tags:
    - xlarge-k8s
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
      when: always
      allow_failure: true
  script:
    - ./proton-mail-uniffi/ios/publish.sh
  dependencies:
    - build-ios
  needs:
    - build-ios

# ------------ Crate Publishing -----------------------------------------------------------------------------------
# Crates are listed in the order they should be published

deploy-proton-api-mail:
  extends: .deploy_to_protonvpn_repository
  image: gitlab.protontech.ch:4567/rust/inbox/docker-images:rust-1.80.0
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  tags:
    - shared-medium
  variables:
    CARGO_PACKAGE_OPTIONS: "--manifest-path proton-api-mail/Cargo.toml"
    CARGO_MANIFEST_OPTIONS: "--manifest-path proton-api-mail/Cargo.toml"
  when: manual

deploy-proton-mail-message-detector:
  extends: .deploy_to_protonvpn_repository
  image: gitlab.protontech.ch:4567/rust/inbox/docker-images:rust-1.80.0
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  variables:
    CARGO_PACKAGE_OPTIONS: "--manifest-path proton-mail-message-detector/Cargo.toml"
    CARGO_MANIFEST_OPTIONS: "--manifest-path proton-mail-message-detector/Cargo.toml"
  when: manual

deploy-proton-mail-html-transformer:
  extends: .deploy_to_protonvpn_repository
  image: gitlab.protontech.ch:4567/rust/inbox/docker-images:rust-1.80.0
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  variables:
    CARGO_PACKAGE_OPTIONS: "--manifest-path proton-mail-html-transformer/Cargo.toml"
    CARGO_MANIFEST_OPTIONS: "--manifest-path proton-mail-html-transformer/Cargo.toml"
  when: manual

deploy-proton-mail-common:
  extends: .deploy_to_protonvpn_repository
  image: gitlab.protontech.ch:4567/rust/inbox/docker-images:rust-1.80.0
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  tags:
    - shared-medium
  variables:
    CARGO_PACKAGE_OPTIONS: "--manifest-path proton-mail-common/Cargo.toml"
    CARGO_MANIFEST_OPTIONS: "--manifest-path proton-mail-common/Cargo.toml"
  when: manual
