image: gitlab.protontech.ch:4567/rust/inbox/docker-images:rust

# sccache location to speed up compilation.
default:
  tags:
    - shared-medium
  cache: &global_cache
    key: sccache
    paths:
      - /tmp/cache


# Config git acccess to other repos
.script-config-git:
  script:
    - git config --global url.https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}.insteadOf https://${CI_SERVER_HOST}
    - git submodule update --init --recursive

stages:
  - lint
  - build
  - doc


.do_fmt_check:
   script:
     - !reference [.script-config-git, script]
     - cargo fmt --check

.do_clippy_check:
   script:
     - !reference [.script-config-git, script]
     - cargo clippy -- -D warnings

.do_proton_mail_uniffi_version:
  script:
    - cd proton_mail_uniffi


format:
  stage: lint
  script:
    - !reference [.do_fmt_check, script]

clippy:
  stage: lint
  script:
    - !reference [.do_clippy_check, script]

build:
  stage: build
  script:
    - !reference [.script-config-git, script]
    - cargo build --release
    - cargo test

build-macos:
  tags:
    - inbox-tart
  image: "inbox-rust:1.76.0"
  stage: build
  script:
    - !reference [.script-config-git, script]
    - cargo build --release
    - cargo test

build-wasm:
  stage: build
  script:
    - !reference [.script-config-git, script]
    - cd proton-mail-wasm
    - CRATE_VERSION=$(cargo pkgid | cut -d "#" -f2)
    - wasm-pack build -d "./web_pkg/$CRATE_VERSION"
  artifacts:
    name: proton-mail-wasm
    paths:
      - proton-mail-wasm/web_pkg
    when: always
    expire_in: 4 hrs

build-ios:
  tags:
    - inbox-tart
  image: "inbox-rust:1.76.0"
  stage: build
  script:
    - !reference [.script-config-git, script]
    - CRATE_VERSION=$(cargo pkgid -p proton-mail-uniffi | cut -d "#" -f2)
    - rust-build/build_ios_framework_uniffi.sh proton-mail-uniffi proton-mail-uniffi/uniffi.toml "./tmp/ios-framework/$CRATE_VERSION"
    - cd "./tmp/ios-framework/$CRATE_VERSION/package" && xcodebuild -scheme proton_mail_uniffi -destination generic/platform=iOS -configuration="Release build"

  artifacts:
    name: proton-mail-ios
    paths:
      - tmp/ios-framework
    when: always
    expire_in: 4 hrs

build-android:
  stage: build
  script:
    - !reference [.script-config-git, script]
    - CRATE_VERSION=$(cargo pkgid -p proton-mail-uniffi | cut -d "#" -f2)
    - rust-build/build_android.sh proton-mail-uniffi proton-mail-uniffi/uniffi.toml "./tmp/android/$CRATE_VERSION"

  artifacts:
    name: proton-mail-android
    paths:
      - ./tmp/android
    when: always
    expire_in: 4 hrs

pages:
  stage: doc
  script:
    - echo "CI_PAGES_URL = ${CI_PAGES_URL}"
    - !reference [.script-config-git, script]
    - cargo doc --workspace --all-features --no-deps
    - rm -rf public
    - mv target/doc public
    - echo "<meta http-equiv=\"refresh\" content=\"0; url=$CI_PAGES_URL/proton_mail_uniffi/index.html\">" > public/index.html
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    # allow to test pages in a MR
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
      allow_failure: true
