mod windows_zones {
    include!(concat!(env!("OUT_DIR"), "/windows_zones.rs"));
}

/// Converts Windows-specific timezone (as generated by Outlook) into a tzdb
/// one.
pub fn windows_to_tzdb(name: &str) -> Option<&'static str> {
    windows_zones::MAP.get(name).map(|name| &**name)
}

#[cfg(test)]
mod tests {
    use test_case::test_case;

    #[test_case("W. Europe Standard Time", Some("Europe/Berlin"))]
    #[test_case("Central European Standard Time", Some("Europe/Warsaw"))]
    #[test_case("Anime Time Zone", None)]
    fn windows_to_tzdb(lhs: &str, rhs: Option<&str>) {
        assert_eq!(rhs, super::windows_to_tzdb(lhs));
    }
}
