use crate::PropertyKind;
use crate::parameters::type_generic::is_type_param;
use crate::parameters::type_related::RelatedType;

#[test]
fn tel_type_enum() {
    assert_eq!(
        RelatedType::new_validated("HoMe").unwrap(),
        RelatedType::Home
    );
    assert_eq!(
        RelatedType::new_validated("WoRk").unwrap(),
        RelatedType::Work
    );
    assert_eq!(
        RelatedType::new_validated("CoNtAcT").unwrap(),
        RelatedType::Contact
    );
    assert_eq!(
        RelatedType::new_validated("AcQuAiNtAnCe").unwrap(),
        RelatedType::Acquaintance
    );
    assert_eq!(
        RelatedType::new_validated("FrIeNd").unwrap(),
        RelatedType::Friend
    );
    assert_eq!(RelatedType::new_validated("MeT").unwrap(), RelatedType::Met);
    assert_eq!(
        RelatedType::new_validated("Co-wOrKeR").unwrap(),
        RelatedType::CoWorker
    );
    assert_eq!(
        RelatedType::new_validated("CoLleAgUe").unwrap(),
        RelatedType::Colleague
    );
    assert_eq!(
        RelatedType::new_validated("Co-rEsIdEnT").unwrap(),
        RelatedType::CoResident
    );
    assert_eq!(
        RelatedType::new_validated("NeIgHbOr").unwrap(),
        RelatedType::Neighbor
    );
    assert_eq!(
        RelatedType::new_validated("ChIlD").unwrap(),
        RelatedType::Child
    );
    assert_eq!(
        RelatedType::new_validated("PaReNt").unwrap(),
        RelatedType::Parent
    );
    assert_eq!(
        RelatedType::new_validated("SiBlInG").unwrap(),
        RelatedType::Sibling
    );
    assert_eq!(
        RelatedType::new_validated("SpOuSe").unwrap(),
        RelatedType::Spouse
    );
    assert_eq!(RelatedType::new_validated("KiN").unwrap(), RelatedType::Kin);
    assert_eq!(
        RelatedType::new_validated("MuSe").unwrap(),
        RelatedType::Muse
    );
    assert_eq!(
        RelatedType::new_validated("CrUsH").unwrap(),
        RelatedType::Crush
    );
    assert_eq!(
        RelatedType::new_validated("DaTe").unwrap(),
        RelatedType::Date
    );
    assert_eq!(
        RelatedType::new_validated("SwEeThEaRt").unwrap(),
        RelatedType::Sweetheart
    );
    assert_eq!(RelatedType::new_validated("Me").unwrap(), RelatedType::Me);
    assert_eq!(
        RelatedType::new_validated("AgEnT").unwrap(),
        RelatedType::Agent
    );
    assert_eq!(
        RelatedType::new_validated("EmErGeNcY").unwrap(),
        RelatedType::Emergency
    );
}

#[test]
fn type_param() {
    assert!(is_type_param(
        &PropertyKind::Related,
        &[
            "contact".to_owned(),
            "acquaintance".to_owned(),
            "friend".to_owned(),
            "met".to_owned(),
            "co-worker".to_owned(),
            "colleague".to_owned(),
            "co-resident".to_owned(),
            "neighbor".to_owned(),
            "child".to_owned(),
            "parent".to_owned(),
            "sibling".to_owned(),
            "spouse".to_owned(),
            "kin".to_owned(),
            "muse".to_owned(),
            "crush".to_owned(),
            "date".to_owned(),
            "sweetheart".to_owned(),
            "me".to_owned(),
            "agent".to_owned(),
            "emergency".to_owned(),
            "work".to_owned(),
            "home".to_owned(),
            "iana-token".to_owned(),
            "x-name".to_owned(),
        ]
    ));
}
