use crate::conversations::tests::conversations::{
    test_address, test_label1, test_label2, MY_ADDRESS_ID, MY_LABEL_ID1, MY_LABEL_ID2,
};
use crate::conversations::tests::utils::TestDBState;
use lazy_static::lazy_static;
use proton_api_mail::domain::{
    AttachmentId, AttachmentMetadata, Conversation, ConversationId, ConversationLabels,
    Disposition, Label, LabelId, LabelType, MessageAddress, MessageId, MessageMetadata,
};
use proton_api_mail::proton_api_core::domain::ProtonBoolean;

lazy_static! {
    pub(super) static ref DELETE_DB_CONV1: ConversationId = ConversationId::from("MyConvId1");
    pub(super) static ref DELETE_DB_CONV2: ConversationId = ConversationId::from("MyConvId2");
}

pub(in crate::conversations) fn new_message_id(num: usize) -> MessageId {
    MessageId::from(format!("MessageId{num}"))
}
pub(in crate::conversations) fn new_test_delete_db_state() -> TestDBState {
    // Conversation 1 has 3 messages, split between 2 labels, 1 is unread  + 1 Attachment(s)
    // Conversation 2 has 2 message in one label, 1 is unread + 0 Attachment(s)
    let conv_id1 = DELETE_DB_CONV1.clone();
    let conv_id2 = DELETE_DB_CONV2.clone();
    TestDBState {
        addresses: vec![test_address()],
        labels: vec![
            test_label1(),
            test_label2(),
            Label {
                id: LabelId::all_mail().clone(),
                parent_id: None,
                name: "All Mail".to_string(),
                path: None,
                color: "".to_string(),
                label_type: LabelType::System,
                notify: Default::default(),
                display: Default::default(),
                sticky: Default::default(),
                expanded: Default::default(),
                order: 5,
            },
        ],
        conversations: vec![
            Conversation {
                id: conv_id1.clone(),
                order: 0,
                subject: String::new(),
                senders: vec![],
                recipients: vec![],
                num_messages: 0,
                num_unread: 0,
                num_attachments: 0,
                expiration_time: 0,
                size: 0,
                labels: vec![
                    ConversationLabels {
                        id: MY_LABEL_ID1.clone(),
                        context_num_unread: 0,
                        context_num_messages: 0,
                        context_time: 0,
                        context_size: 0,
                        context_num_attachments: 0,
                    },
                    ConversationLabels {
                        id: MY_LABEL_ID2.clone(),
                        context_num_unread: 0,
                        context_num_messages: 0,
                        context_time: 0,
                        context_size: 0,
                        context_num_attachments: 0,
                    },
                ],
                display_snooze_reminder: false,
                attachments_metadata: vec![],
                attachment_info: Default::default(),
            },
            Conversation {
                id: conv_id2.clone(),
                order: 0,
                subject: String::new(),
                senders: vec![],
                recipients: vec![],
                num_messages: 0,
                num_unread: 0,
                num_attachments: 0,
                expiration_time: 0,
                size: 0,
                labels: vec![ConversationLabels {
                    id: MY_LABEL_ID2.clone(),
                    context_num_unread: 0,
                    context_num_messages: 0,
                    context_time: 0,
                    context_size: 0,
                    context_num_attachments: 0,
                }],
                display_snooze_reminder: false,
                attachments_metadata: vec![],
                attachment_info: Default::default(),
            },
        ],
        messages: vec![
            // Conv1 Message 1
            MessageMetadata {
                id: new_message_id(0),
                conversation_id: conv_id1.clone(),
                address_id: MY_ADDRESS_ID.clone(),
                order: 0,
                label_ids: vec![MY_LABEL_ID1.clone()],
                external_id: None,
                subject: "Message subject".to_string(),
                sender: MessageAddress {
                    address: "bar@bar.com".to_string(),
                    name: "".to_string(),
                    is_proton: Default::default(),
                    display_sender_image: Default::default(),
                    is_simple_login: Default::default(),
                    bimi_selector: None,
                },
                to_list: vec![MessageAddress {
                    address: "foo@bar.com".to_string(),
                    name: "".to_string(),
                    is_proton: Default::default(),
                    display_sender_image: Default::default(),
                    is_simple_login: Default::default(),
                    bimi_selector: None,
                }],
                cc_list: vec![],
                bcc_list: vec![],
                reply_tos: vec![],
                flags: 0,
                time: 100,
                size: 512,
                unread: Default::default(),
                is_replied: Default::default(),
                is_replied_all: Default::default(),
                is_forwarded: Default::default(),
                expiration_time: 0,
                num_attachments: 1,
                attachments_metadata: vec![AttachmentMetadata {
                    id: AttachmentId::from("MyAttachId"),
                    size: 1024,
                    name: "text.text".to_string(),
                    mime_type: "text/plain".to_string(),
                    disposition: Disposition::Inline,
                }],
            },
            // Conv1 Message 2
            MessageMetadata {
                id: new_message_id(1),
                conversation_id: conv_id1.clone(),
                address_id: MY_ADDRESS_ID.clone(),
                order: 1,
                label_ids: vec![MY_LABEL_ID2.clone()],
                external_id: None,
                subject: "FW: Message subject".to_string(),
                sender: MessageAddress {
                    address: "foo@bar.com".to_string(),
                    name: "".to_string(),
                    is_proton: Default::default(),
                    display_sender_image: Default::default(),
                    is_simple_login: Default::default(),
                    bimi_selector: None,
                },
                to_list: vec![MessageAddress {
                    address: "omega@bar.com".to_string(),
                    name: "".to_string(),
                    is_proton: Default::default(),
                    display_sender_image: Default::default(),
                    is_simple_login: Default::default(),
                    bimi_selector: None,
                }],
                cc_list: vec![],
                bcc_list: vec![],
                reply_tos: vec![],
                flags: 0,
                time: 200,
                size: 100,
                unread: Default::default(),
                is_replied: Default::default(),
                is_replied_all: Default::default(),
                is_forwarded: ProtonBoolean::True,
                expiration_time: 0,
                num_attachments: 0,
                attachments_metadata: vec![],
            },
            // Conv1 Message 3
            MessageMetadata {
                id: new_message_id(3),
                conversation_id: conv_id1.clone(),
                address_id: MY_ADDRESS_ID.clone(),
                order: 1,
                label_ids: vec![MY_LABEL_ID1.clone()],
                external_id: None,
                subject: "RE: FW: Message subject".to_string(),
                sender: MessageAddress {
                    address: "omega@bar.com".to_string(),
                    name: "".to_string(),
                    is_proton: Default::default(),
                    display_sender_image: Default::default(),
                    is_simple_login: Default::default(),
                    bimi_selector: None,
                },
                to_list: vec![MessageAddress {
                    address: "foo@bar.com".to_string(),
                    name: "".to_string(),
                    is_proton: Default::default(),
                    display_sender_image: Default::default(),
                    is_simple_login: Default::default(),
                    bimi_selector: None,
                }],
                cc_list: vec![],
                bcc_list: vec![],
                reply_tos: vec![],
                flags: 0,
                time: 400,
                size: 300,
                unread: ProtonBoolean::True,
                is_replied: Default::default(),
                is_replied_all: Default::default(),
                is_forwarded: Default::default(),
                expiration_time: 0,
                num_attachments: 0,
                attachments_metadata: vec![],
            },
            // Conv1 Message 4
            MessageMetadata {
                id: new_message_id(10),
                conversation_id: conv_id1.clone(),
                address_id: MY_ADDRESS_ID.clone(),
                order: 0,
                label_ids: vec![MY_LABEL_ID1.clone()],
                external_id: None,
                subject: "FW: Message subject".to_string(),
                sender: MessageAddress {
                    address: "bar@bar.com".to_string(),
                    name: "".to_string(),
                    is_proton: Default::default(),
                    display_sender_image: Default::default(),
                    is_simple_login: Default::default(),
                    bimi_selector: None,
                },
                to_list: vec![MessageAddress {
                    address: "foo@bar.com".to_string(),
                    name: "".to_string(),
                    is_proton: Default::default(),
                    display_sender_image: Default::default(),
                    is_simple_login: Default::default(),
                    bimi_selector: None,
                }],
                cc_list: vec![],
                bcc_list: vec![],
                reply_tos: vec![],
                flags: 0,
                time: 450,
                size: 100,
                unread: Default::default(),
                is_replied: Default::default(),
                is_replied_all: Default::default(),
                is_forwarded: Default::default(),
                expiration_time: 0,
                num_attachments: 0,
                attachments_metadata: vec![],
            },
            // Conv2 Message 1
            MessageMetadata {
                id: new_message_id(4),
                conversation_id: conv_id2.clone(),
                address_id: MY_ADDRESS_ID.clone(),
                order: 1,
                label_ids: vec![MY_LABEL_ID2.clone()],
                external_id: None,
                subject: "Test".to_string(),
                sender: MessageAddress {
                    address: "sponge.bob@square.pants".to_string(),
                    name: "".to_string(),
                    is_proton: Default::default(),
                    display_sender_image: Default::default(),
                    is_simple_login: Default::default(),
                    bimi_selector: None,
                },
                to_list: vec![MessageAddress {
                    address: "patrick@start.fish".to_string(),
                    name: "".to_string(),
                    is_proton: Default::default(),
                    display_sender_image: Default::default(),
                    is_simple_login: Default::default(),
                    bimi_selector: None,
                }],
                cc_list: vec![MessageAddress {
                    address: "venture@bros.com".to_string(),
                    name: "".to_string(),
                    is_proton: Default::default(),
                    display_sender_image: Default::default(),
                    is_simple_login: Default::default(),
                    bimi_selector: None,
                }],
                bcc_list: vec![],
                reply_tos: vec![],
                flags: 0,
                time: 300,
                size: 300,
                unread: ProtonBoolean::False,
                is_replied: Default::default(),
                is_replied_all: Default::default(),
                is_forwarded: Default::default(),
                expiration_time: 0,
                num_attachments: 0,
                attachments_metadata: vec![],
            },
            // Conv2 Message 2
            MessageMetadata {
                id: new_message_id(5),
                conversation_id: conv_id2.clone(),
                address_id: MY_ADDRESS_ID.clone(),
                order: 1,
                label_ids: vec![MY_LABEL_ID2.clone()],
                external_id: None,
                subject: "RE: Test".to_string(),
                sender: MessageAddress {
                    address: "venture@bros.com".to_string(),
                    name: "".to_string(),
                    is_proton: Default::default(),
                    display_sender_image: Default::default(),
                    is_simple_login: Default::default(),
                    bimi_selector: None,
                },
                to_list: vec![MessageAddress {
                    address: "sponge.bob@square.pants".to_string(),
                    name: "".to_string(),
                    is_proton: Default::default(),
                    display_sender_image: Default::default(),
                    is_simple_login: Default::default(),
                    bimi_selector: None,
                }],
                cc_list: vec![],
                bcc_list: vec![],
                reply_tos: vec![],
                flags: 0,
                time: 800,
                size: 300,
                unread: ProtonBoolean::True,
                is_replied: Default::default(),
                is_replied_all: Default::default(),
                is_forwarded: Default::default(),
                expiration_time: 0,
                num_attachments: 0,
                attachments_metadata: vec![],
            },
        ],
    }
}
