#![allow(clippy::must_use_candidate)]

#[cfg(test)]
#[path = "tests/proton_schemes.rs"]
mod tests;

use crate::css_parser::{parse_style_attribute, parse_stylesheet};
use kuchikiki::iter::NodeEdge;
use kuchikiki::{ExpandedName, NodeData, NodeRef};
use lightningcss::printer::PrinterOptions;
use lightningcss::values::url::Url;
use lightningcss::visitor::{Visit, VisitTypes, Visitor};
use std::convert::Infallible;
use std::sync::LazyLock;
use tracing::warn;

static IMAGE_ATTRIBUTES: LazyLock<[ExpandedName; 5]> = LazyLock::new(|| {
    [
        crate::utils::attribute_name("src"),
        crate::utils::attribute_name("srcset"),
        crate::utils::attribute_name("background"),
        crate::utils::attribute_name("poster"),
        crate::utils::attribute_name("data-src"),
    ]
});

/// Transform image URLs from HTTP/HTTPS to proton-http/proton-https schemes.
pub fn transform_to_proton_schemes(document: NodeRef) -> u64 {
    let mut count = 0;

    let style_attr = crate::utils::attribute_name("style");

    for node in document.traverse_inclusive() {
        let NodeEdge::Start(node_ref) = node else {
            continue;
        };

        let Some(element) = node_ref.as_element() else {
            continue;
        };

        if element.name.local.as_ref() == "style" {
            node_ref.children().for_each(|child| {
                if let NodeData::Text(text) = child.data() {
                    count += transform_stylesheet_to_proton(&mut text.borrow_mut());
                }
            });
        }

        let mut attributes = element.attributes.borrow_mut();
        for attr_name in IMAGE_ATTRIBUTES.iter() {
            if let Some(attr) = attributes.map.get_mut(attr_name) {
                if attr_name.local.as_ref() == "srcset" {
                    count += transform_srcset_to_proton(&mut attr.value);
                } else {
                    count += transform_url_to_proton(&mut attr.value);
                }
            }
        }

        if let Some(attr) = attributes.map.get_mut(&style_attr) {
            count += transform_style_attribute_to_proton(&mut attr.value);
        }
    }

    count
}

/// Transform image URLs from proton-http/proton-https schemes back to HTTP/HTTPS.
pub fn transform_from_proton_schemes(document: NodeRef) -> u64 {
    let mut count = 0;
    let style_attr = crate::utils::attribute_name("style");

    for node in document.traverse_inclusive() {
        let NodeEdge::Start(node_ref) = node else {
            continue;
        };

        let Some(element) = node_ref.as_element() else {
            continue;
        };

        if element.name.local.as_ref() == "style" {
            node_ref.children().for_each(|child| {
                if let NodeData::Text(text) = child.data() {
                    count += transform_stylesheet_from_proton(&mut text.borrow_mut());
                }
            });
        }

        let mut attributes = element.attributes.borrow_mut();
        for attr_name in IMAGE_ATTRIBUTES.iter() {
            if let Some(attr) = attributes.map.get_mut(attr_name) {
                if attr_name.local.as_ref() == "srcset" {
                    count += transform_srcset_from_proton(&mut attr.value);
                } else {
                    count += transform_url_from_proton(&mut attr.value);
                }
            }
        }

        if let Some(attr) = attributes.map.get_mut(&style_attr) {
            count += transform_style_attribute_from_proton(&mut attr.value);
        }
    }

    count
}

fn transform_url_to_proton(url: &mut String) -> u64 {
    // Preserve empty URLs - they might be generated by the disable-content pass
    if url.is_empty() {
        return 0;
    }

    let base = url::Url::parse("https://dummy.com").unwrap();

    let Ok(resolved) = base.join(url) else {
        return 0;
    };

    match resolved.scheme() {
        "https" => {
            *url = resolved
                .to_string()
                .replacen("https://", "proton-https://", 1);
            1
        }
        "http" => {
            *url = resolved
                .to_string()
                .replacen("http://", "proton-http://", 1);
            1
        }
        _ => 0,
    }
}

fn transform_url_from_proton(url: &mut String) -> u64 {
    if url.starts_with("proton-https://") {
        *url = url.replacen("proton-https://", "https://", 1);
        1
    } else if url.starts_with("proton-http://") {
        *url = url.replacen("proton-http://", "http://", 1);
        1
    } else {
        0
    }
}

fn transform_srcset_to_proton(srcset: &mut String) -> u64 {
    let mut count = 0;
    let mut elements = Vec::new();

    for entry in srcset.trim().split(',') {
        let values = entry.trim().splitn(2, ' ').collect::<Vec<&str>>();
        if values.is_empty() {
            continue;
        }

        let mut url = values[0].to_string();
        count += transform_url_to_proton(&mut url);

        if values.len() > 1 {
            elements.push(format!("{} {}", url, values[1]));
        } else {
            elements.push(url);
        }
    }

    *srcset = elements.join(", ");
    count
}

fn transform_srcset_from_proton(srcset: &mut String) -> u64 {
    let mut count = 0;
    let mut elements = Vec::new();

    for entry in srcset.trim().split(',') {
        let values = entry.trim().splitn(2, ' ').collect::<Vec<&str>>();
        if values.is_empty() {
            continue;
        }

        let mut url = values[0].to_string();
        count += transform_url_from_proton(&mut url);

        if values.len() > 1 {
            elements.push(format!("{} {}", url, values[1]));
        } else {
            elements.push(url);
        }
    }

    *srcset = elements.join(", ");
    count
}

fn transform_stylesheet_to_proton(css: &mut String) -> u64 {
    let Ok(mut sheet) = parse_stylesheet(css).inspect_err(|e| {
        warn!("StyleSheet parsing failed: {}", e);
    }) else {
        return 0;
    };

    let mut visitor = ProtonSchemeVisitor::new(true);
    let _ = sheet.visit(&mut visitor);

    if !visitor.has_changes {
        return 0;
    }

    let Ok(patched) = sheet.to_css(PrinterOptions::default()) else {
        warn!("Failed to convert style sheet to css value");
        return 0;
    };

    let patched_code = patched.code;
    drop(sheet);

    *css = patched_code;
    visitor.change_count
}

fn transform_stylesheet_from_proton(css: &mut String) -> u64 {
    let Ok(mut sheet) = parse_stylesheet(css).inspect_err(|e| {
        warn!("StyleSheet parsing failed: {}", e);
    }) else {
        return 0;
    };

    let mut visitor = ProtonSchemeVisitor::new(false);
    let _ = sheet.visit(&mut visitor);

    if !visitor.has_changes {
        return 0;
    }

    let Ok(patched) = sheet.to_css(PrinterOptions::default()) else {
        warn!("Failed to convert style sheet to css value");
        return 0;
    };

    let patched_code = patched.code;
    drop(sheet);

    *css = patched_code;
    visitor.change_count
}

fn transform_style_attribute_to_proton(css: &mut String) -> u64 {
    let Ok(mut style_attribute) = parse_style_attribute(css).inspect_err(|e| {
        warn!("Style attribute parsing failed: {}", e);
    }) else {
        return 0;
    };

    let mut visitor = ProtonSchemeVisitor::new(true);
    let _ = style_attribute.visit(&mut visitor);

    if !visitor.has_changes {
        return 0;
    }

    let Ok(patched) = style_attribute.to_css(PrinterOptions::default()) else {
        warn!("Failed to convert style attribute to css value");
        return 0;
    };

    let patched_code = patched.code;
    drop(style_attribute);

    *css = patched_code;
    visitor.change_count
}

fn transform_style_attribute_from_proton(css: &mut String) -> u64 {
    let Ok(mut style_attribute) = parse_style_attribute(css).inspect_err(|e| {
        warn!("Style attribute parsing failed: {}", e);
    }) else {
        return 0;
    };

    let mut visitor = ProtonSchemeVisitor::new(false);
    let _ = style_attribute.visit(&mut visitor);

    if !visitor.has_changes {
        return 0;
    }

    let Ok(patched) = style_attribute.to_css(PrinterOptions::default()) else {
        warn!("Failed to convert style attribute to css value");
        return 0;
    };

    let patched_code = patched.code;
    drop(style_attribute);

    *css = patched_code;
    visitor.change_count
}

struct ProtonSchemeVisitor {
    has_changes: bool,
    change_count: u64,
    to_proton: bool,
}

impl ProtonSchemeVisitor {
    fn new(to_proton: bool) -> Self {
        Self {
            has_changes: false,
            change_count: 0,
            to_proton,
        }
    }
}

impl<'i> Visitor<'i> for ProtonSchemeVisitor {
    type Error = Infallible;

    fn visit_types(&self) -> VisitTypes {
        VisitTypes::URLS
    }

    fn visit_url(&mut self, url: &mut Url<'i>) -> Result<(), Self::Error> {
        let url_str = url.url.to_string();
        let mut new_url = url_str.clone();

        let changed = if self.to_proton {
            transform_url_to_proton(&mut new_url)
        } else {
            transform_url_from_proton(&mut new_url)
        };

        if changed > 0 {
            url.url = new_url.into();
            self.has_changes = true;
            self.change_count += changed;
        }

        Ok(())
    }
}
